### ISSUE TITLE
Loading never finishes

### ISSUE THREAD

**Issue by ntucker** [microsoft/deoptexplorer-vscode#12]
After I fixed sourcemaps the log loading never finishes

## Reproducing

1. Checkout https://github.com/data-client/rest-hooks
2. corepack enable
3. yarn install
4. yarn build
5. cd examples/benchmark
6. yarn build
7. yarn start:deopt

Now load v8.log

It has progress for a while but eventually just disappears. No error

https://github.com/microsoft/deoptexplorer-vscode/assets/866147/fa2d564a-44e1-4b89-b3cf-9a74c9cb5d0a

## Platform info

Win11, WSL2, Ubuntu, Node 20.1

64GB memory 7950x CPU

Logfile size: 109.33MB

**Comment by ntucker** [comment]
Reduced the logsize to 24MB by removing some stuff it does and it still doesn't load

**Comment by rbuckton** [comment]
You may be seeing some slowness related to map parsing. I have a fix for #14 that includes a fix for map details parsing that may help.

**Comment by rbuckton** [comment]
I just published v1.0.3 of Deopt Explorer. Can you try that one out and let me know if that helped?

**Comment by ntucker** [comment]
New version finishes the bottom right loading bar much faster! However, the top loading bar (shown in video) still sits there forever. I don't think it's a performance issue. I think it errorred and doesn't have a way of showing the error.

**Comment by rbuckton** [comment]
I've been unable to repro this locally, but I've addressed some related issues that may help as well. Could you try your scenario again with v1.1.1, which published just now?

**Comment by ntucker** [comment]
@rbuckton yup, with the new version it loads, and some of the files show up as 'the editor could not be opened because the file could not be found'. this makes me think https://github.com/microsoft/deoptexplorer-vscode/pull/24 was likely the fix. Thanks for this!

In a related note, it looks like my sourcemaps are outputting examples/src/normalize.ts rather than packages/normalizr/src/normalize.ts.... any ideas what might cause that? I don't expect any help here as this is not the concern on the library, but if you happened to have ideas around that it would be much appreciated. Thanks again for the great library and great support here!
