### ISSUE TITLE
Error: Cannot find module 'winreg'

### ISSUE THREAD

**Issue by HarveyYu-Pro** [microsoft/deoptexplorer-vscode#17]
Hi!I installed it on my Mac and used it, but it got wrong when I used it. Is this a bug or is it just me?
![image](https://github.com/microsoft/deoptexplorer-vscode/assets/39736085/5b4fb060-d1d9-489f-bfc0-bf1275a9914f)

**Comment by JorgeLNJunior** [comment]
Same here, running in Manjaro Linux.

**Comment by rbuckton** [comment]
This should be fixed in the most recent version. Can you give `dexnode@1.2.0` a try and see if it still occurs?

**Comment by rbuckton** [comment]
Actually, there is a typo in the package.json that is causing this. I'll publish a new version shortly.

**Comment by rbuckton** [comment]
This should now be fixed as of `dexnode@1.2.1`.
