### ISSUE TITLE
Feature request: Support actual typing compare with typescript

### ISSUE THREAD

**Issue by SieR-VR** [microsoft/deoptexplorer-vscode#19]
Hello, I just knew about this with [article](https://devblogs.microsoft.com/typescript/introducing-deopt-explorer/), and much impressed!

## What problem solved with this feature?
Thesedays, much js/ts packages from package managers are running. And we can find not only js but also ts packages are that may have wrong runtime types (e g. `as any` or `as unknown as` in ts). But with runtime deopt, we can fix most of actual type errors.

## My thinking about implementation
I guess types in v8 is different from typescript types. (I thought like this cause I don't know about v8 well)
So may need conversion between v8 internal type and typescript type(ts.Type).

Is it well-match with main purpose of this project? or should be seperated project?

**Comment by rbuckton** [comment]
I'm not sure it's a good match for this project, and while you could certainly use some of this functionality to roughly correlate some V8 runtime information to TS types, there are quite a few limitations. You might be able to check that V8 map witnessed by an IC has _at least_ the required properties in a TS type, but excess properties might only indicate an inherited type. The type information V8 provides in its logs is also fairly limited, with only `smi`, `heap`, and some infrequent `map` references (which only occur in extremely stable maps with properties pointing to other extremely stable maps).

I do have some interest in extracting some of the functionality to build something like a GitHub action to target specific sections of a codebase and flag on polymorphism/megamorphism to catch changes you might make elsewhere in your code that would effect performance-critical code, but that may be a ways off.
