### ISSUE TITLE
How to collect info from browser?

### ISSUE THREAD

**Issue by CheloXL** [microsoft/deoptexplorer-vscode#8]
It would be nice to know which command line you can use to start a chromium based browser to collect the same information (or if this can be collected via devtools, where to find it).

**Comment by rbuckton** [comment]
I will look into updating the documentation. You can usually pass V8 flags through Chromium using the `--js-flags="..."` option, i.e.:

```
chrome --js-flags="--log-deopt --log-ic --log-maps --log-maps-details --logfile=v8.log --no-logfile-per-isolate"
```
