### ISSUE TITLE
Support sourcemaps?

### ISSUE THREAD

**Issue by ntucker** [microsoft/deoptexplorer-vscode#9]
I compile my benchmarks with webpack so it does all the normal optimizations I expect; but that means when I click the file it cannot find it

**Comment by rbuckton** [comment]
Is it possible the source file not exist at the path pointed to by the source map? Alternatively, does your source map contain embedded sources?

If you have a public project I could use to generate a repro, that would help to narrow down the cause.

**Comment by rbuckton** [comment]
I should add, Deopt Explorer does support source maps but we've had a few reports of source-map related issues that we're looking into.

**Comment by ntucker** [comment]
Ah, I didn't even realize it got the filenames wrong. For reference https://github.com/data-client/rest-hooks is the repo. The folder is /examples/benchmark with script 'start:deopt'.

I gotta look into webpack sourcemap control for monorepos...

**Comment by ntucker** [comment]
Well now the logs won't load...no error message just infinite loading. I'll open a new issue for that
